
local Colors = {
  background = "NONE",
  foreground = "#ebdbb2",
  foreground_1 = "#83a598",
  secondary = "NONE",
  tertiary = "#FFFFFF",
  selection = "#1c1c1c",
  functions = "#fe8019",
  keywords = "#9797fc",
  types = "#f5f507",
  strings = "#ff7373",
  comments = "#2a9c2a",
  macros = "#b254c7",
  constants = "#fab36b",
}

return {
  terminal_colors = true,
  italic = {
    emphasis = true,
    comments = true,
    folds = true,
    strings = false,
  },
  overrides = {
    Normal = { bg = Colors.background, fg = Colors.foreground },
    Function = { fg = Colors.functions },
    Keyword = { fg = Colors.keywords },
    Type = { fg = Colors.types },
    cType = { fg = Colors.types },
    cppType = { fg = Colors.types },
    cppStructure = { fg = Colors.keywords },
    cStructure = { fg = Colors.keywords },
    String = { fg = Colors.strings },
    Comment = { fg = Colors.comments, italic = true },
    Macro = { fg = Colors.macros },
    Statement = { fg = Colors.keywords },
    cStatement = { fg = Colors.keywords },
    cppStatiment = { fg = Colors.keywords },
    Label = { fg = Colors.keywords },
    cLabel = { fg = Colors.keywords },
    cppLabel = { fg = Colors.keywords },
    Modifier = { fg = Colors.keywords },
    cModifier = { fg = Colors.keywords },
    cppModifier = { fg = Colors.keywords },
    Constant = { fg = Colors.constants },
    cConstant = { fg = Colors.keywords },
    cppConstant = { fg = Colors.keywords },
    Typedef = { fg = Colors.types },
    cTypedef = { fg = Colors.keywords},
    cppTypedef = { fg = Colors.keywords },
    cExceptions = {fg = Colors.keywords },
    cppExceptions = {fg = Colors.keywords },
    Include = { fg = Colors.macros },
    StorageClass = { fg = Colors.keywords },
    Boolean = { fg = Colors.keywords },
    Conditional = { fg = Colors.keywords },
    Repeat = { fg = Colors.keywords },
    Define = { fg = Colors.keywords },
    PreProc = { fg = Colors.macros },
    PreCondit = { fg = Colors.macros },

    Identifier = { fg = Colors.foreground },
    cIdentifier = { fg = Colors.foreground },
    cppIdentifier = { fg = Colors.foreground },

    Operator = { fg = Colors.keywords },
    cOperator = { fg = Colors.keywords },
    cppOperator = { fg = Colors.keywords },

    Numbers = { fg = Colors.foreground_1},
    cNumbers = { fg = Colors.foreground_1 },
    cppNumber = { fg = Colors.foreground_1 },

    Float = { fg = Colors.foreground_1},
    cFloat = { fg = Colors.foreground_1 },
    cppFloat = { fg = Colors.foreground_1 },

    Character = { fg = Colors.strings },
    cCharacter = { fg = Colors.strings },
    cppCharacter = { fg = Colors.strings },

    SnippetTabstopActive = {fg = "#FFC857", bg = "NONE"},
    LspSignatureActiveParameter = {fg = "#FFFFFF", bg = "NONE", bold = true},
    -- Editor
    SignColumn = { bg = Colors.secondary },
    EndOfBuffer = { bg = Colors.background },

    CursorLine = { bg = Colors.selection },
    CursorColumn = { bg = Colors.selection},

    FloatBorder = { bg = "NONE", fg = "#3c3836" },
    Pmenu = { bg = Colors.secondary, fg = Colors.foreground, blend = 0, bold = true},
    PmenuSel = { bg = Colors.selection, fg = Colors.tertiary, blend = 0, bold = true},
    NormalFloat = { bg = Colors.secondary, fg = Colors.tertiary },

    --DiagnosticFloatingError = { fg = "#ff0000", bg = "NONE", bold = true },
    --DiagnosticFloatingWarn = { fg = "#ffff00", bg = "NONE", bold = true },
    --DiagnosticFloatingInfo = { fg = "#00ffff", bg = "NONE", bold = true },
    --DiagnosticFloatingHint = { fg = "#00ff00", bg = "NONE", bold = true },
    --DiagnosticVirtualTextError = { fg = Colors.foreground, bg = "NONE", bold = true },
    --DiagnosticVirtualTextWarn = { fg = Colors.foreground, bg = "NONE", bold = true },
    --DiagnosticVirtualTextInfo = { fg = Colors.foreground, bg = "NONE", bold = true },
    --DiagnosticVirtualTextHint = { fg = Colors.foreground, bg = "NONE", bold = true },

    ["@lsp.type.namespace.c"] = { fg = Colors.foreground },
    ["@lsp.type.namespace.cpp"] = { fg = Colors.foreground },
    ["@lsp.type.variable.c"] = { fg = Colors.foreground_1 },
    ["@lsp.type.variable.cpp"] = { fg = Colors.foreground_1 },
    ["@lsp.type.property.c"] = { fg = Colors.foreground },
    ["@lsp.type.property.cpp"] = { fg = Colors.foreground },
    --["@lsp.type.parameter.c"] = { fg = Colors.foreground },
    --["@lsp.type.parameter.cpp"] = { fg = Colors.foreground },
 
    ["@nospell"] = { fg = Colors.foreground_1, bold = false, italic = true },
    ["@spell.markdown"] = {fg = Colors.foreground_1, bold = false, italic = true},
    ["@markup.heading.3.markdown"] = {fg = Colors.foreground_1, bold = false, italic = true},
    ["@markup.raw.block.markdown"] = {fg = Colors.foreground_1, bold = false, italic = true},
    
    --["@text.literal.markdown"] = {fg = Colors.foreground_1, bold = true, italic = true},
    --["@text.reference.markdown"] = {fg = Colors.foreground_1, bold = true, italic = true},
    --["@text.title.markdown"] = {fg = Colors.foreground_1, bold = true, italic = true},
    --["@text.uri.markdown"] = {fg = Colors.foreground_1, bold = true, italic = true},
  },
}



